"use client";
import { Inter } from "next/font/google";
import "./adminStyle.css";
import Aos from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";
import Header from "@/(components)/AdminComponents/Header";
import Sidebar from "@/(components)/AdminComponents/Sidebar";
import Offcanvas from "@/(components)/AdminComponents/Offcanvas";
import Footer from "@/(components)/AdminComponents/Footer";

const inter = Inter({ subsets: ["latin"] });

//export const metadata = {
//  title: 'Create Next App',
//description: 'Generated by create next app',
//}

export default function AdminLayout({ children }) {
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  useEffect(() => {
    Aos.init({
      duration: 800,
      once: false,
    });
  });
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Sidebar />
        <Offcanvas />
        {children}
        <Footer />
      </body>
    </html>
  );
}
