"use client";
import { Inter } from "next/font/google";
import "./passQStyle.css";
import Aos from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";
import PassQNavbar from "@/(components)/ZallaPassQComponents/Navbar";

const inter = Inter({ subsets: ["latin"] });

//export const metadata = {
//  title: 'Create Next App',
//description: 'Generated by create next app',
//}

export default function StudentsLayout({ children }) {
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  useEffect(() => {
    Aos.init({
      duration: 800,
      once: false,
    });
  });
  return (
    <html lang="en">
      <body className={inter.className}>
        <PassQNavbar />
        {children}
      </body>
    </html>
  );
}
